### ISSUE TITLE
Refactor Gig Card Component

### ISSUE THREAD

**Issue by devadigapratham** [devadigapratham/SolveRR-frontend#2]
Refactor the GigCard component for improved readability and maintainability. Consider breaking down the component into smaller, reusable sub-components and organize the code to enhance modularity.

**Comment by kdb04** [comment]
Can i get this assigned?

**Comment by devadigapratham** [comment]
@kdb04 assigned the issue to you

**Comment by sid-nc** [comment]
can i get assigned to this

**Comment by akdino** [comment]
could you please assigne this to me

**Comment by devadigapratham** [comment]
reassigned to @sid-nc

**Comment by kdb04** [comment]
can i get this assigned
