### ISSUE TITLE
Add Transitions and Animations to Slides

### ISSUE THREAD

**Issue by devadigapratham** [devadigapratham/SolveRR-frontend#3]
Implement smooth transitions and animations for the slides. Add effects such as fade-ins or slide-ins to enhance the user experience when transitioning between slides in the carousel.

**Comment by anirudhsudhir** [comment]
Could you assign this to me?

**Comment by ProSai45** [comment]
could you assign me this??

**Comment by devadigapratham** [comment]
@ProSai8055 assigned the issue

**Comment by sid-nc** [comment]
can i get assigned to this

**Comment by harveen-10** [comment]
can you assign this to me

**Comment by devadigapratham** [comment]
reassigned to @harveen-10

**Comment by KaashviR** [comment]
Assign this to me please

**Comment by diishanbhag** [comment]
can u please assign this to me
