### ISSUE TITLE
Add Hover Effects to Cat Card

### ISSUE THREAD

**Issue by devadigapratham** [devadigapratham/SolveRR-frontend#4]
Implement subtle hover effects for the CatCard component to provide visual feedback to users. This could include changing background colors, adding shadows, or animating the card on hover for a more interactive experience.

**Comment by maazshakeel** [comment]
@devadigapratham Hey, I'd love to work on this issue, can you assign it to me?

**Comment by shreyahegde26** [comment]
can i get assigned to this please??

**Comment by Shriya285** [comment]
can i get assigned?

**Comment by Prajwal-creator007** [comment]
can i get assigned to this?

**Comment by SuchitraShankar07** [comment]
could i be assigned to this

**Comment by 7Akshu77** [comment]
can I get assigned to this issue

**Comment by devadigapratham** [comment]
@shreyahegde26  assigned the issue to you

**Comment by harveen-10** [comment]
can i get assigned this issue?

**Comment by sid-nc** [comment]
can i get assigned to this

**Comment by saivihitha17** [comment]
can i get it ?

**Comment by neethanm** [comment]
can i get get assigned to #4?

**Comment by nik2203** [comment]
@devadigapratham Could I be assigned to this issue please?
